name = "InverseDistanceWeighting"
uuid = "6a8e3230-34bb-5a86-b9da-9f7447a06da5"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.2.3"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["GeoStatsBase", "Pkg", "VisualRegressionTests", "Plots", "ImageMagick", "QuartzImageIO", "Test"]

[compat]
GeoStatsBase = "≥ 0.5.0"
julia = "1"
